
from django.urls import path
from . import views

urlpatterns = [
    path('login/',views.login),
    path('changepwd/',views.changepwd),
    path('verifytutor/',views.verifytutor),
    path('approvedtutor/',views.approvedtutor),
    path('rejectedtutor/', views.rejectedtutor),
    path('addstudent/',views.addstudent),
    path('editstudent/',views.editstudent),
    path('viewstudent/',views.viewstudent),
    path('addsubject/',views.addsubject),
    path('editsubject/',views.editsubject),
    path('viewsubject/',views.viewsubject),
    path('addtimetable/',views.addtimetable),
    path('edit_timetable/',views.edit_timetable),
    path('viewtimetable/',views.viewtimetable),
    path('viewattendance/',views.viewattendance),
    path('getpaymentnotification/', views.getpaymentnotification),
    path('viewpaymentnotification/', views.viewpaymentnotification),
    path('addbill/', views.addbill),
    path('viewbil/',views.viewbill),
    path('viewcomplaint/',views.viewcomplaint),
    path('addreplay/',views.addreplay),
    path('viewfeedback/',views.viewfeedback),
#=============================================================================
    path('signup/',views.signup),
    path('Login/',views.login),
    path('change_password/',views.change_password),
    path('editprofile/',views.editprofile),
    path('view_student/', views.view_student),
    path('view_subject/', views.view_subject),
    path('view_timetable/',views.view_timetable),
    path('getclasslink/', views.getclasslink),
    path('viewclasslink/',views.viewclasslink),
    path('addattendance/', views.addattendance),
    path('editattendance/', views.editattendance),
    path('view_attendance/', views.view_attendance),
    path('addnotification/', views.addnotification),
    path('viewnotification/', views.viewnotification),
    path('addhomework/', views.addhomework),
    path('viewhomework/', views.viewhomework),
    path('viewanswer/', views.viewanswer),
    path('view_feedback/', views.view_feedback),

#=============================================================================

    path('Login/',views.login),
    path('change_pwd/', views.change_pwd),
    path('viewprofile/', views.viewprofile),
    path('view_sub/', views.view_sub),
    path('student_viewtimetable/', views.student_viewtimetable),
    path('view_classlink/', views.view_classlink),
    path('student_viewattendance/', views.student_viewattendance),
    path('view_notification/', views.view_notification),
    path('view_homework/', views.view_homework),
    path('submitanswer/', views.submitanswer),
    path('view_answer/', views.view_answer),
    path('addcomplaint/',views.addcomplaint),
    path('view_complaint/', views.view_complaint),
    path('viewreplay/', views.viewreplay),
    path('sendfeedback/', views.sendfeedback),
    path('student_viewfeedback/',views.student_viewfeedback),

#=============================================================================
    path('Login/',views.login),
    path('parent_viewstudent/', views.parent_viewstudent),
    path('parent_viewattendance/', views.parent_viewattendance),
    path('parent_viewtimetable/', views.parent_viewtimetable),
    path('view_paymentnotification/', views.view_paymentnotification),
    path('view_bill/', views.view_bill),

]